export const tabOrder = {
  noWorkItemSelected: {
    refineTextBox: 0,
    workQueueListItem: 1,
    browserTab: 2,
    menu: 3,
    renewalHome: 4,
    inTake: 5,
    dataEntry: 6,
    dataReview: 7,
    assembly: 8,
    productReview: 9,
    billing: 10,
    clinical: 11,
    prescriber: 12,
    stock: 13,
    notification: 14,
    userAvatar: 15,
    appSwitcher: 16,
    refine: 17,
    filter: 18,
  },
  workItemSelected: {
    appSwitcher: 3,
    userAvatar: 4,
    notification: 5,
    stock: 6,
    refineTextBox: 2,
    browserTab: 17,
    menu: 16,
    renewalHome: 15,
    inTake: 14,
    dataEntry: 13,
    dataReview: 12,
    assembly: 11,
    productReview: 10,
    billing: 9,
    clinical: 8,
    prescriber: 7,
  },
};
